Section "ServerFlags"
    Option "AutoAddDevices" "false"
    Option "AutoEnableDevices" "false"
    Option "AllowMouseOpenFail" "true"
    Option "AIGLX" "false"
EndSection

Section "Module"
    Disable "glx"
EndSection

Section "Device"
    Identifier "Linux framebuffer"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
EndSection

Section "Screen"
    Identifier "Desktop"
    Device "Linux framebuffer"
    DefaultDepth 24
EndSection
