CONFIG_ARMV8_A_NS=y
CONFIG_KERNEL_VM_SIZE=0x20000000
CONFIG_FPU=y
CONFIG_FPU_SHARING=y
CONFIG_PICOLIBC=y
CONFIG_PICOLIBC_ASSERT_VERBOSE=y
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=33554432
CONFIG_MAIN_STACK_SIZE=131072
CONFIG_HEAP_MEM_POOL_SIZE=1048576
CONFIG_QEMU=y
CONFIG_QEMU_HOST_HEARTBEAT=y
CONFIG_ASSERT=y
CONFIG_POSIX_THREADS=y
CONFIG_POSIX_THREAD_THREADS_MAX=8
CONFIG_MAX_PTHREAD_MUTEX_COUNT=64
CONFIG_MAX_PTHREAD_COND_COUNT=32
CONFIG_POSIX_API=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_MAX_FILE_NAME=32
CONFIG_POSIX_FILE_SYSTEM=y
CONFIG_ZVFS_OPEN_ADD_SIZE_POSIX=16
