#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Bootstrap the project without installing Python packages globally."""

import argparse
import json
import shlex
import subprocess
import sys
import venv

from environment import (ROOT, VENV, TOOLS, STATE, SDK_VERSION, command_env,
                         doctor, find_sdk, host_problems, sdk_qemu)


def run(*args, **kwargs):
    subprocess.run(args, cwd=ROOT, check=True, **kwargs)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--doctor", action="store_true")
    args = parser.parse_args()
    if args.doctor:
        doctor()
        return
    problems = host_problems()
    if problems:
        raise RuntimeError("\n".join(problems) + "\nInstall host packages with make host-deps first.")

    print("Preparing isolated Python environment...", flush=True)
    # Creating over an existing venv retains installed packages, and disables
    # system-site-packages if an older development setup enabled it.
    venv.EnvBuilder(with_pip=True, symlinks=True).create(VENV)
    python = str(VENV / "bin/python")
    env = command_env(require_sdk=False)
    run(python, "-m", "pip", "install", "-r", "requirements-bootstrap.txt", env=env)
    run(python, "scripts/project.py", "init", env=env)
    # The module requirement list includes Zephyr's pinned base requirements and
    # our tests, rather than downloading every optional Zephyr subsystem's tools.
    env["ZEPHYR_BASE"] = str(ROOT / "upstream/zephyr")
    run(python, "-m", "west", "packages", "-m", "qemu_on_zephyr", "pip", "--install", env=env)
    run(python, "scripts/project.py", "prepare", env=env)
    env["ZEPHYR_BASE"] = str(ROOT / "build/sources/zephyr")

    sdk = find_sdk()
    if sdk is None or not sdk_qemu(sdk).is_file():
        destination = sdk or TOOLS / f"zephyr-sdk-{SDK_VERSION}"
        TOOLS.mkdir(exist_ok=True)
        run(python, "-m", "west", "sdk", "install", "--version", SDK_VERSION,
            "--install-dir", str(destination), "--gnu-toolchains", "aarch64-zephyr-elf", env=env)
        sdk = find_sdk()
        if sdk is None or not sdk_qemu(sdk).is_file():
            raise RuntimeError("SDK installation did not produce the AArch64 toolchain and host QEMU")
    TOOLS.mkdir(exist_ok=True)
    temporary = STATE.with_suffix(".tmp")
    temporary.write_text(json.dumps({"sdk": str(sdk), "sdk_version": SDK_VERSION}, indent=4) + "\n")
    temporary.replace(STATE)
    configured = command_env()
    exports = ["# Generated by make setup; source this file for direct west commands."]
    for key in ("VIRTUAL_ENV", "ZEPHYR_BASE", "ZEPHYR_TOOLCHAIN_VARIANT", "ZEPHYR_SDK_INSTALL_DIR",
                "QEMU_SYSTEM_AARCH64", "QEMU_BIN_PATH"):
        exports.append(f"export {key}={shlex.quote(configured[key])}")
    exports.append(f'export PATH={shlex.quote(str(VENV / "bin"))}:"$PATH"')
    (TOOLS / "env.sh").write_text("\n".join(exports) + "\n")
    run(python, "scripts/project.py", "assets", env=command_env())
    doctor()
    print("Setup complete. Run make run or make check; no shell activation is needed.")


if __name__ == "__main__":
    try:
        main()
    except (RuntimeError, subprocess.CalledProcessError, OSError) as error:
        sys.exit(str(error))
