CONFIG_ARM64_EL2=y
CONFIG_ARMV8_A_NS=y
CONFIG_FPU=y
CONFIG_FPU_SHARING=y
CONFIG_PICOLIBC=y
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=8388608
CONFIG_MAIN_STACK_SIZE=65536
CONFIG_HEAP_MEM_POOL_SIZE=1048576
CONFIG_QEMU=y
CONFIG_QEMU_PL011_PROBE=y
CONFIG_ASSERT=y
CONFIG_POSIX_THREADS=y
CONFIG_POSIX_THREAD_THREADS_MAX=8
CONFIG_POSIX_API=y
